<?php

namespace FutbolBundle\Repository;

/**
 * EntrenadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrenadorRepository extends \Doctrine\ORM\EntityRepository
{
}
