<?php

namespace FutbolBundle\Repository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
