<?php

namespace PruebaBundle\Repository;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasRepository extends \Doctrine\ORM\EntityRepository
{
}
