<?php

namespace PruebaBundle\Repository;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends \Doctrine\ORM\EntityRepository
{
}
