entrenador_index:
    path:     /
    defaults: { _controller: "FutbolBundle:Entrenador:index" }
    methods:  GET

entrenador_show:
    path:     /{id}/show
    defaults: { _controller: "FutbolBundle:Entrenador:show" }
    methods:  GET

entrenador_new:
    path:     /new
    defaults: { _controller: "FutbolBundle:Entrenador:new" }
    methods:  [GET, POST]

entrenador_edit:
    path:     /{id}/edit
    defaults: { _controller: "FutbolBundle:Entrenador:edit" }
    methods:  [GET, POST]

entrenador_delete:
    path:     /{id}/delete
    defaults: { _controller: "FutbolBundle:Entrenador:delete" }
    methods:  DELETE
